import type { HeatZone, MapLayer, SpatialEntity, SpatialFlow } from "@/platform/maps/core/map-types";

export const mockSpatialEntities: SpatialEntity[] = [
  { id: "map-region-midwest", entityType: "Region", displayName: "Mock Midwest", coordinates: { latitude: 41.8781, longitude: -87.6298, isApproximate: true }, confidence: "medium", relatedEntities: ["graph-region-midwest"], sourceIds: ["graph-source-4"], isMock: true },
  { id: "map-state-plain", entityType: "State", displayName: "Mock State Territory", coordinates: { latitude: 39.5, longitude: -98.35, isApproximate: true }, confidence: "medium", relatedEntities: ["graph-state-plain"], sourceIds: ["graph-source-4"], isMock: true },
  { id: "map-city-river", entityType: "City", displayName: "Mock River City", coordinates: { latitude: 39.0997, longitude: -94.5786, isApproximate: true }, confidence: "medium", relatedEntities: ["graph-city-river"], sourceIds: ["graph-source-4"], isMock: true },
  { id: "map-campus-state", entityType: "Campus", displayName: "Mock State Campus", coordinates: { latitude: 38.9517, longitude: -92.3341, isApproximate: true }, confidence: "high", relatedEntities: ["graph-team-state", "graph-school-state"], sourceIds: ["graph-source-1"], isMock: true },
  { id: "map-cluster-central", entityType: "GeographicCluster", displayName: "Mock Central Cluster", coordinates: { latitude: 40.0, longitude: -89.0, isApproximate: true }, confidence: "medium", relatedEntities: ["graph-player-alpha"], sourceIds: ["graph-source-2"], isMock: true },
  { id: "map-territory-north", entityType: "RecruitingTerritory", displayName: "Mock North Territory", coordinates: { latitude: 44.9, longitude: -93.2, isApproximate: true }, confidence: "medium", relatedEntities: ["graph-recruiting-2026"], sourceIds: ["graph-source-4"], isMock: true },
  { id: "map-pipeline-central-state", entityType: "TalentPipeline", displayName: "Mock Central to State Pipeline", coordinates: { latitude: 40.7, longitude: -91.0, isApproximate: true }, confidence: "medium", relatedEntities: ["graph-highschool-central", "graph-team-state"], sourceIds: ["graph-source-4"], isMock: true },
  { id: "map-flow-alpha", entityType: "TransferFlow", displayName: "Mock Player Alpha Flow", coordinates: { latitude: 39.8, longitude: -93.0, isApproximate: true }, confidence: "medium", relatedEntities: ["graph-player-alpha", "graph-team-state"], sourceIds: ["graph-source-2"], isMock: true }
];

const [region, state, city, campus, cluster, territory, pipeline, flowEntity] = mockSpatialEntities;

export const mockMapLayers: MapLayer[] = [
  { id: "layer-transfer", layerType: "transfer_activity", displayName: "Transfer Activity", description: "Mock transfer movement and portal activity.", enabledByDefault: true, confidence: "medium", entityIds: [flowEntity.id, campus.id], sourceIds: ["graph-source-2"], isMock: true },
  { id: "layer-recruiting", layerType: "recruiting_activity", displayName: "Recruiting Activity", description: "Mock recruiting footprint and pipeline signals.", enabledByDefault: true, confidence: "medium", entityIds: [territory.id, pipeline.id], sourceIds: ["graph-source-4"], isMock: true },
  { id: "layer-conference", layerType: "conference_movement", displayName: "Conference Movement", description: "Mock conference inflow and outflow signals.", enabledByDefault: false, confidence: "medium", entityIds: [region.id], sourceIds: ["graph-source-2"], isMock: true },
  { id: "layer-coaching", layerType: "coaching_connections", displayName: "Coaching Connections", description: "Mock coach-region relationship density.", enabledByDefault: false, confidence: "low", entityIds: [territory.id], sourceIds: ["graph-source-3"], isMock: true },
  { id: "layer-hometowns", layerType: "player_hometowns", displayName: "Player Hometowns", description: "Mock hometown clusters.", enabledByDefault: false, confidence: "medium", entityIds: [city.id], sourceIds: ["graph-source-4"], isMock: true },
  { id: "layer-highschool", layerType: "high_school_pipelines", displayName: "High School Pipelines", description: "Mock high school to college pipelines.", enabledByDefault: true, confidence: "medium", entityIds: [pipeline.id], sourceIds: ["graph-source-4"], isMock: true },
  { id: "layer-portal", layerType: "portal_entries", displayName: "Portal Entries", description: "Mock portal entry density.", enabledByDefault: true, confidence: "medium", entityIds: [cluster.id], sourceIds: ["graph-source-2"], isMock: true },
  { id: "layer-commitments", layerType: "commitments", displayName: "Commitments", description: "Mock commitments; projection-sensitive and review-gated.", enabledByDefault: false, confidence: "low", entityIds: [campus.id], sourceIds: ["graph-source-5"], isMock: true },
  { id: "layer-visits", layerType: "official_visits", displayName: "Official Visits", description: "Mock official visit geography.", enabledByDefault: true, confidence: "medium", entityIds: [campus.id, city.id], sourceIds: ["graph-source-2"], isMock: true },
  { id: "layer-nil", layerType: "nil_activity", displayName: "NIL Activity", description: "Mock NIL geography; never confirmed without source labels.", enabledByDefault: false, confidence: "low", entityIds: [state.id], sourceIds: ["graph-source-5"], isMock: true },
  { id: "layer-prediction", layerType: "prediction_activity", displayName: "Prediction Activity", description: "Mock projection movement geography.", enabledByDefault: false, confidence: "medium", entityIds: [flowEntity.id], sourceIds: ["graph-source-3"], isMock: true },
  { id: "layer-watchlist", layerType: "watchlist_activity", displayName: "Watchlist Activity", description: "Mock personalized map layer placeholder.", enabledByDefault: false, confidence: "unknown", entityIds: [region.id], sourceIds: [], isMock: true },
  { id: "layer-heat", layerType: "heat_maps", displayName: "Heat Maps", description: "Mock spatial heat zones.", enabledByDefault: true, confidence: "medium", entityIds: ["heat-midwest"], sourceIds: ["graph-source-2"], isMock: true },
  { id: "layer-density", layerType: "relationship_density", displayName: "Relationship Density", description: "Mock graph relationship density overlay.", enabledByDefault: true, confidence: "medium", entityIds: [region.id, campus.id], sourceIds: ["graph-source-1"], isMock: true }
];

export const mockSpatialFlows: SpatialFlow[] = [
  { id: "flow-player-school", flowType: "player_to_school", displayName: "Mock Player to Mock State", origin: city, destination: campus, confidence: "medium", strength: 74, evidenceCount: 4, sourceCount: 3, timelineSupport: ["mock timeline: hometown", "mock timeline: visit"], relatedGraphRelationshipIds: ["rel-player-visit", "rel-player-interest"], isMock: true },
  { id: "flow-school-school", flowType: "school_to_school", displayName: "Mock School to State Flow", origin: campus, destination: state, confidence: "medium", strength: 61, evidenceCount: 3, sourceCount: 2, timelineSupport: ["mock timeline: portal movement"], relatedGraphRelationshipIds: ["rel-team-gained", "rel-team-lost"], isMock: true },
  { id: "flow-conference-conference", flowType: "conference_to_conference", displayName: "Mock Conference Movement", origin: region, destination: campus, confidence: "medium", strength: 58, evidenceCount: 2, sourceCount: 2, timelineSupport: ["mock timeline: conference trend"], relatedGraphRelationshipIds: ["rel-team-conference"], isMock: true },
  { id: "flow-state-school", flowType: "state_to_school", displayName: "Mock State Retention Flow", origin: state, destination: campus, confidence: "medium", strength: 69, evidenceCount: 3, sourceCount: 2, timelineSupport: ["mock timeline: state retention"], relatedGraphRelationshipIds: ["rel-player-region"], isMock: true },
  { id: "flow-highschool-college", flowType: "high_school_to_college", displayName: "Mock Central to College Pipeline", origin: pipeline, destination: campus, confidence: "medium", strength: 76, evidenceCount: 4, sourceCount: 3, timelineSupport: ["mock timeline: pipeline"], relatedGraphRelationshipIds: ["rel-player-highschool"], isMock: true },
  { id: "flow-coach-region", flowType: "coach_to_region", displayName: "Mock Coach Regional Footprint", origin: territory, destination: region, confidence: "low", strength: 49, evidenceCount: 2, sourceCount: 1, timelineSupport: ["mock timeline: coach footprint"], relatedGraphRelationshipIds: ["rel-coach-recruited"], isMock: true }
];

export const mockHeatZones: HeatZone[] = [
  { id: "heat-midwest", entityType: "HeatZone", displayName: "Mock Midwest Heat Zone", coordinates: { latitude: 41.2, longitude: -88.5, isApproximate: true }, confidence: "medium", relatedEntities: ["graph-region-midwest"], sourceIds: ["graph-source-2"], intensity: 78, metricLabel: "Mock transfer activity", isMock: true },
  { id: "heat-north", entityType: "HeatZone", displayName: "Mock North Pipeline Heat", coordinates: { latitude: 44.1, longitude: -93.0, isApproximate: true }, confidence: "medium", relatedEntities: ["graph-recruiting-2026"], sourceIds: ["graph-source-4"], intensity: 64, metricLabel: "Mock recruiting activity", isMock: true }
];
